app = 'protohkr'
primary_region = 'arn'

[build]
  [build.args]
    GO_VERSION = '1.24.4'

[[services]]
  internal_port = 5000
  protocol = 'tcp'

  [[services.ports]]
    port = 5000

  [services.concurrency]
    type = 'connections'
    hard_limit = 200
    soft_limit = 150

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  # The minimum amount that can be used
  memory_mb = 256
